Update and delete Item
BritonKelley/SanaApp pull request #23
Opened 2023-11-07 01:11 UTC by mason414

Added the ability to update and delete and item from the item exploration view. Merged with @dmitchelldm74 code to be able to use the api without the http client.

2023-11-07 01:40 UTC, dmitchelldm74 commented on src/components/ItemUpdate/ItemUpdate.tsx
>        navigate('/explore-items');
* @mason414 Probably better to use `onSuccess()` here instead:
https://tanstack.com/query/latest/docs/react/guides/mutations#mutation-side-effects

2023-11-07 03:59 UTC, dmitchelldm74 requested changes

2023-11-07 03:59 UTC, dmitchelldm74 commented on src/components/ItemUpdate/ItemUpdate.tsx
> +          <form onSubmit={
@mason414

2023-11-17 20:18 UTC, dmitchelldm74 approved these changes

2023-11-17 20:20 UTC, tswizzle110 approved these changes

2023-11-17 20:21 UTC, tswizzle110 approved these changes

2023-11-17 20:21 UTC, tswizzle110 approved these changes

2023-11-17 20:28 UTC, closed without merging